CREATE SEQUENCE IF NOT EXISTS school_seq START 1;
CREATE SEQUENCE IF NOT EXISTS specialization_seq START 1;
CREATE SEQUENCE IF NOT EXISTS department_seq START 1;
CREATE SEQUENCE IF NOT EXISTS course_seq START 1;
CREATE SEQUENCE IF NOT EXISTS exam_seq START 1;
CREATE SEQUENCE IF NOT EXISTS exam_slot_seq START 1;
CREATE SEQUENCE IF NOT EXISTS staff_duty_seq START 1;
CREATE SEQUENCE IF NOT EXISTS role_seq START 1;