spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/exam_duty_allocation?currentSchema=common,examduty
    username: examduty_user
    password: examduty123  
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: examduty
    open-in-view: false
server:
  port: 8081
logging:
  level:
    com.exam.duty.backend: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
jwt:
  secret: myVerySecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLongForDockerEnvironment
  expiration: 86400000